version: '3.5'

services:
  notesgo:
    container_name: notesgo
    image: mdouchement/standardfile:0.6.8
    networks:
      - traefik_default
    volumes:
      - ./standardfile.yml:/etc/standardfile/standardfile.yml
      - ./standardfile.db:/etc/standardfile/standardfile.db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notesgo.rule=Host(`notes.hugowillaume.com`)"
      - "traefik.http.routers.notesgo.entrypoints=websecure"
      - "traefik.http.routers.notesgo.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.notesgo.loadbalancer.server.port=5000"

  notes-extensions:
    container_name: notes-extensions
    image: halverneus/static-file-server:v1.8.4
    networks:
      - traefik_default
    volumes:
      - ./standardnotes-extensions/public:/web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notes-ext.rule=Host(`notes-extensions.hugowillaume.com`) || (Host(`notes.hugowillaume.com`) && PathPrefix(`/extensions`))"
      - "traefik.http.routers.notes-ext.entrypoints=websecure"
      - "traefik.http.routers.notes-ext.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.notes-ext.loadbalancer.server.port=8080"

networks:
  traefik_default:
    external: true 
