version: '3.7'

services:
  terraria:
    image: ghcr.io/beardedio/terraria:tshock-5.1.3
    container_name: terraria
    ports:
      - '7777:7777'
      - '7878:7878'
    restart: unless-stopped
    env_file: ./env.file
    volumes:
      - ./config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.terraria.rule=Host(`terraria.hugowillaume.com`)"
      - "traefik.http.routers.terraria.entrypoints=terraria"
      - "traefik.http.services.terraria.loadbalancer.server.port=7777"

      - "traefik.http.routers.terraria_api.rule=Host(`terraria.hugowillaume.com`)"
      - "traefik.http.routers.terraria_api.entrypoints=terraria_api"
      - "traefik.http.services.terraria_api.loadbalancer.server.port=7878"      
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
         
